### ISSUE TITLE
CAN'T REPRODUCE RESULT

### ISSUE THREAD

**Issue by N-Kingsley** [astier/MFEC#1]
I train your own agent from scratch, but I can't get the same good result as the result in 'agents/Qbert-v0_06-25-06-05-38/results.csv'. Why is that？My result are as follows:

epoch, episodes, frames, reward_sum, reward_avg, reward_max
1,46,101240,31400,683,1050
2,36,99748,34075,947,1125
3,34,101328,35375,1040,1125
4,34,98740,32925,968,1150
5,30,100616,31675,1056,1150
6,31,100416,31025,1001,1150
7,31,100404,31475,1015,1150
8,30,100540,32400,1080,1150
9,29,99980,31750,1095,1150
10,29,97432,31000,1069,1150
11,31,101108,30675,990,1150
12,36,100060,36025,1001,1475
13,32,102100,45200,1412,2000
14,29,96300,45350,1564,2000
15,30,103220,50050,1668,2000
16,28,98972,48825,1744,2025
17,28,99800,48950,1748,2050
18,29,98692,47300,1631,2025
19,28,100180,49900,1782,2050
20,29,100372,48700,1679,2050

**Comment by astier** [comment]
Did you change any parameter except *AGENT_PATH* and *RENDER*? Could you please download this project again, build a new conda-environment, keep all the default settings and only change the following two parameters:
```
AGENT_PATH = ''
RENDER = False
```
You should be able to reproduce the exact same agent after 11 epochs like the one in the project. I personally just retrained and uploaded the agent and it worked for me. You should only get different results if you change training-relevant parameters like *SEED*, *EPSILON*, etc.

**Comment by astier** [comment]
Obviously I set the seed such that a reasonable agent can be trained and also reproduced. However, if you use different seeds or set it to *None* it can also happen that the agent gets stuck in a local minima. He might still be able to get out of it but the probability can be very low resulting in ridiculously long training-times.

**Comment by astier** [comment]
Do you still have the problem? Otherwise I will close this issue in a week or so.

**Comment by N-Kingsley** [comment]
Thank you for your patience, I have no problems.

**Comment by astier** [comment]
Cool. Thanks.
